[package]
    name = "cc-downloader"
    version = "0.6.1"
    edition = "2024"
    authors = ["Pedro Ortiz Suarez <pedro@commoncrawl.org>"]
    description = "A polite and user-friendly downloader for Common Crawl data."
    license = "MIT OR Apache-2.0"
    rust-version = "1.93"
    readme = "README.md"
    homepage = "https://commoncrawl.org"
    repository = "https://github.com/commoncrawl/cc-downloader"
    documentation = "https://docs.rs/cc-downloader"

[dependencies]
    clap = { version = "4.6.1", features = ["derive"] }
    flate2 = "1.1.9"
    futures = "0.3.32"
    indicatif = "0.18.4"
    regex = "1.12.3"
    reqwest = { version = "0.13.2" }
    reqwest-middleware = "0.5.1"
    reqwest-retry = "0.9.1"
    tokio = { version = "1.52.1", features = ["full"] }
    tokio-util = { version = "0.7.18", features = ["compat"] }
    url = "2.5.8"

[dev-dependencies]
    serde = { version = "1.0.228", features = ["derive"] }
    reqwest = { version = "0.13.2", features = ["json"] }
